### ISSUE TITLE
Refactor `Patitioning::into_local_partition` into context method + add thread-based partitioning

### ISSUE THREAD

**Issue by juntyr** [juntyr/necsim-rust#106]
Ideally the difference to process-based partitioning would be to allow live event reporting ... somehow ... efficiently?

**Comment by MomoLangenstein** [comment]
The memory footprint could be reduced for in-memory scenarios by using `Arc<T>` around the heap allocations in the habitat, dispersal sampler, and turnover sampler (would also make backups much faster) - would require `Arc<T>` support in `const-type-layout` and `rust-cuda`.

**Comment by MomoLangenstein** [comment]
Ideally this would be accompanied by also using MPI with internal parallelism, i.e. creating the universe only inside the closure. However, `rsmpi` does not yet support this, and MPI can only spawn new executables, not fork an existing process. Also, the semantics of distributing simulation parameters and collecting (merging) results would have to be clarified.

**Comment by juntyr** [comment]
https://github.com/juntyr/necsim-rust/commit/92d8ef16540a935ad8b72c33a1bbfe7e47e35445 is another small step in this direction, by removing knowledge about the local partition from before (outside) the partitioning context method [^1].

[^1]: MPI partitioning gets special treatment for now by exposing a special method to peek beforehand if the running code will be the root partition, which it currently uses to turn off logging for other partitions.
